<a href="https://colab.research.google.com/github/madhavisahani852/-Lead-Scoring-and-CRM-system/blob/main/Lead_Scoring_%26_CRM_Intelligence_Tool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lead Scoring & CRM Intelligence Tool

This project uses Machine Learning to predict the probability
that a lead will become a customer.

The probability is converted into a score from 0 to 100.

The lead is then classified as:

- HIGH
- MEDIUM
- LOW

In [1]:
# Import Libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
# Create Sample Lead Data

data = {
    "website_visits": [10, 2, 8, 1, 7, 3, 9, 2, 6, 4],
    "pricing_visits": [5, 1, 4, 0, 3, 1, 5, 1, 3, 2],
    "demo_requested": [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    "converted": [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)

df

   website_visits  pricing_visits  demo_requested  converted
0              10               5               1          1
1               2               1               0          0
2               8               4               1          1
3               1               0               0          0
4               7               3               1          1
5               3               1               0          0
6               9               5               1          1
7               2               1               0          0
8               6               3               1          1
9               4               2               0          0

In [3]:
# Understand the Dataset

print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset:")
display(df)

Dataset Shape:
(10, 4)

Column Names:
Index(['website_visits', 'pricing_visits', 'demo_requested', 'converted'], dtype='object')

Missing Values:
website_visits    0
pricing_visits    0
demo_requested    0
converted         0
dtype: int64

Dataset:

   website_visits  pricing_visits  demo_requested  converted
0              10               5               1          1
1               2               1               0          0
2               8               4               1          1
3               1               0               0          0
4               7               3               1          1
5               3               1               0          0
6               9               5               1          1
7               2               1               0          0
8               6               3               1          1
9               4               2               0          0

In [4]:
# Separate Features and Target

X = df[
    [
        "website_visits",
        "pricing_visits",
        "demo_requested"
    ]
]

y = df["converted"]

print("Features (X):")
display(X)

print("\nTarget (y):")
display(y)

Features (X):

   website_visits  pricing_visits  demo_requested
0              10               5               1
1               2               1               0
2               8               4               1
3               1               0               0
4               7               3               1
5               3               1               0
6               9               5               1
7               2               1               0
8               6               3               1
9               4               2               0

Target (y):

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
8    1
9    0
Name: converted, dtype: int64

In [5]:
# Create Machine Learning Model

model = LogisticRegression()

print("ML Model Created Successfully!")

ML Model Created Successfully!

In [6]:
# Train the Machine Learning Model

model.fit(X, y)

print("Model Training Completed!")

Model Training Completed!

In [7]:
# Create a New Lead

new_lead = pd.DataFrame({
    "website_visits": [9],
    "pricing_visits": [4],
    "demo_requested": [1]
})

print("New Lead:")
display(new_lead)

New Lead:

   website_visits  pricing_visits  demo_requested
0               9               4               1

In [8]:
# Predict Conversion Probability

probability = model.predict_proba(new_lead)[0][1]

print("Conversion Probability:", probability)
print("Conversion Percentage:", probability * 100, "%")

Conversion Probability: 0.9913409426084029
Conversion Percentage: 99.13409426084029 %

In [9]:
# Convert Probability into Lead Score

score = probability * 100

print("Lead Score:", score, "/ 100")

Lead Score: 99.13409426084029 / 100

In [10]:
# Assign Lead Priority

if score >= 80:
    priority = "HIGH"

elif score >= 50:
    priority = "MEDIUM"

else:
    priority = "LOW"

print("Lead Score:", score)
print("Priority:", priority)

Lead Score: 99.13409426084029
Priority: HIGH

In [11]:
# Create Final Lead Result

result = {
    "probability": round(probability, 2),
    "score": round(score, 2),
    "priority": priority
}

print(result)

{'probability': np.float64(0.99), 'score': np.float64(99.13), 'priority': 'HIGH'}

In [12]:
# Create Lead Scoring Function

def score_lead(model, lead):

    # Get probability
    probability = model.predict_proba(lead)[0][1]

    # Convert probability to score
    score = probability * 100

    # Assign priority
    if score >= 80:
        priority = "HIGH"

    elif score >= 50:
        priority = "MEDIUM"

    else:
        priority = "LOW"

    return probability, score, priority

In [13]:
# Test Lead Scoring Function

probability, score, priority = score_lead(
    model,
    new_lead
)

print("Probability:", round(probability, 2))
print("Score:", round(score, 2))
print("Priority:", priority)

Probability: 0.99
Score: 99.13
Priority: HIGH

In [14]:
# Test Multiple Leads

lead_1 = pd.DataFrame({
    "website_visits": [10],
    "pricing_visits": [5],
    "demo_requested": [1]
})

lead_2 = pd.DataFrame({
    "website_visits": [5],
    "pricing_visits": [2],
    "demo_requested": [0]
})

lead_3 = pd.DataFrame({
    "website_visits": [1],
    "pricing_visits": [0],
    "demo_requested": [0]
})

In [15]:
# Score All Leads

leads = [lead_1, lead_2, lead_3]

for i, lead in enumerate(leads, start=1):

    probability, score, priority = score_lead(
        model,
        lead
    )

    print("Lead", i)
    print("Probability:", round(probability * 100, 2), "%")
    print("Score:", round(score, 2), "/ 100")
    print("Priority:", priority)
    print("-" * 30)

Lead 1
Probability: 99.79 %
Score: 99.79 / 100
Priority: HIGH
------------------------------
Lead 2
Probability: 40.73 %
Score: 40.73 / 100
Priority: LOW
------------------------------
Lead 3
Probability: 0.56 %
Score: 0.56 / 100
Priority: LOW
------------------------------

In [16]:
# Create Simple Explanation

if priority == "HIGH":

    print("Why is this lead important?")
    print("- High chance of conversion")
    print("- Sales team should contact this lead quickly")

elif priority == "MEDIUM":

    print("Why is this lead important?")
    print("- Moderate chance of conversion")
    print("- Sales team should follow up")

else:

    print("Why is this lead important?")
    print("- Low chance of conversion")
    print("- Lead has lower priority")

Why is this lead important?
- Low chance of conversion
- Lead has lower priority

In [17]:
# Display Final Lead Information

print("========== LEAD SCORE ==========")

print("Conversion Probability:",
      round(probability * 100, 2), "%")

print("Lead Score:",
      round(score, 2), "/ 100")

print("Priority:",
      priority)

print("================================")

========== LEAD SCORE ==========
Conversion Probability: 0.56 %
Lead Score: 0.56 / 100
Priority: LOW
================================